runtime: nodejs18  # Use the correct Node.js runtime environment
env: standard

automatic_scaling:
  min_idle_instances: 1  # Minimum number of idle instances to be maintained
  max_idle_instances: 2  # Maximum number of idle instances to be maintained
  min_instances: 1       # Minimum number of instances to be maintained under any condition
  max_instances: 5       # Maximum number of instances to be created under load

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

env_variables:
  NODE_ENV: 'production'

handlers:
- url: /(.*\.(js|css|json|png|jpg|jpeg|svg|gif|ico|woff|woff2|ttf|map|pdf))$
  static_files: app_public/dist/app_public/browser/\1
  upload: app_public/dist/app_public/browser/.*\.(js|css|json|png|jpg|jpeg|svg|gif|ico|woff|woff2|ttf|map|pdf)$
- url: /.*
  static_files: app_public/dist/app_public/browser/index.html
  upload: app_public/dist/app_public/browser/index.html
